# Generated by Django 6.1 on 2026-08-21 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('author', models.CharField(blank=True, default='Admin User', max_length=150)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('date', models.CharField(blank=True, default='', max_length=60)),
                ('views', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('seoTitle', models.CharField(blank=True, default='', max_length=250)),
                ('metaDescription', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('interest', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='General', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('attachments', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=150)),
                ('listingType', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='Sale', max_length=20)),
                ('price', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=200)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Sold', 'Sold'), ('Rented', 'Rented')], default='Published', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('amenities', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('builtYear', models.PositiveIntegerField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, default='Dev Nevell Osborne', max_length=150)),
                ('agentRole', models.CharField(blank=True, default='Senior Property Consultant', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, default='Verified Client', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=20)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.CharField(max_length=60)),
                ('fuel', models.CharField(blank=True, default='', max_length=50)),
                ('transmission', models.CharField(blank=True, default='', max_length=50)),
                ('power', models.CharField(blank=True, default='', max_length=50)),
                ('range', models.CharField(blank=True, default='', max_length=50)),
                ('drivetrain', models.CharField(blank=True, default='', max_length=100)),
                ('specifications', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Sold', 'Sold')], default='Published', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Admin User', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('role', models.CharField(blank=True, default='Super Admin', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.vehicle')),
            ],
        ),
    ]
